version: '3.8'

# 完整版本 - 包含前端构建
# 如需纯后端部署，请使用预构建镜像或CI/CD流水线

services:
  # 邮件管理系统主服务（包含前端构建）
  email-system:
    image: ghcr.io/rankgice/new-email/app:latest
    container_name: email-system
    restart: unless-stopped
    ports:
      - "8080:8080"    # Web管理界面和API
      - "25:25"        # SMTP接收端口 (MTA) - 接收外部邮件
      - "587:587"      # SMTP提交端口 (MSA) - 用户发送邮件
      - "993:993"      # IMAP端口 (SSL) - 邮件客户端访问
    volumes:
      - ./data:/app/data
      - ./etc:/app/etc
      - ./logs:/app/data/logs
    environment:
      - TZ=Asia/Shanghai
      - MINIO_ENDPOINT=minio:9000
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - email-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MinIO对象存储（用于文件存储）
  minio:
    image: minio/minio:latest
    container_name: email-minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    networks:
      - email-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

# 网络配置
networks:
  email-network:
    driver: bridge

# 数据卷
volumes:
  minio_data:
    driver: local
